version: "3.9"

services:
  backend:
    image: pibech/catchup-backend:latest
    container_name: catchup-social_core
    restart: always
    env_file:
      - .env
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings_DefaultConnection=${DB_CONNECTION_STRING}
    depends_on:
      - database
    ports:
      - "8080:8080"
      - "8081:8081"
    networks:
      - local

  database:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: catchup-db
    restart: always
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=${MSSQL_SA_PASSWORD}
    ports:
      - "1433:1433"
    volumes:
      - mssql_data:/var/opt/mssql
    networks:
      - local

  reverse-proxy:
    build: ./
    container_name: catchup-proxy
    restart: always
    ports:
      - "8443:443" # https
      - "8585:80" # http
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
    environment:
      - DUCKDNS_TOKEN=${DUCKDNS_TOKEN}
    networks:
      - local

networks:
  local:

volumes:
  mssql_data:
